#include <bits/stdc++.h>
#define _ ios_base::sync_with_stdio(0);cin.tie(0);

#define clr(y,z)        memset(y,z,sizeof(y))


using namespace std;


class BadNeighbors {
public:
    int dp[40][2], n;
    vector <int> d;
    int rec(int pos, int add)
    {
        if(pos+add>=n) return 0;
        int &ret = dp[pos][add];
        if(~ret) return ret;

        ret = max(rec(pos+1, add), d[pos]);
        if(pos == 0) add = 1;
        for (int i = pos+2; i<n; i+=2)
            ret = max(ret, rec(i, add)+d[pos]);
        return ret;
    }

	int maxDonations(vector <int> donations) {
		n = donations.size();
		d = donations;
		clr(dp,-1);
		return rec(0,0);
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <int> p0, bool hasAnswer, int p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p0[i];
	}
	cout << "}";
	cout << "]" << endl;
	BadNeighbors *obj;
	int answer;
	obj = new BadNeighbors();
	clock_t startTime = clock();
	answer = obj->maxDonations(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p1 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;

	vector <int> p0;
	int p1;

	{
	// ----- test 0 -----
	int t0[] = {10,3,2,5,7,8};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 19;
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 1 -----
	int t0[] = {11,15};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 15;
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 2 -----
	int t0[] = {7,7,7,7,7,7,7};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 21;
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 3 -----
	int t0[] = {1,2,3,4,5,1,2,3,4,5};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 16;
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 4 -----
	int t0[] = {94,40,49,65,21,21,106,80,92,81,679,4,61,6,237,12,72,74,29,95,265,35,47,1,61,397,52,72,37,51,1,81,45,435,7,36,57,86,81,72};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 2926;
	all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
	// ------------------
	}

	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
//
// The old song declares "Go ahead and hate your neighbor", and the residents of
// Onetinville have taken those words to heart.  Every resident hates his next-door
// neighbors on both sides.  Nobody is willing to live farther away from the town's
// well than his neighbors, so the town has been arranged in a big circle around
// the well.  Unfortunately, the town's well is in disrepair and needs to be restored.  You
// have been hired to collect donations for the Save Our Well fund.
//
//
//
// Each of the town's residents is willing to donate a certain amount, as specified in the vector <int>
// donations, which is listed in clockwise order around the well.  However, nobody is willing to
// contribute to a fund to which his neighbor has also contributed.  Next-door neighbors are always listed
// consecutively in donations, except that the first and last entries in donations are also
// for next-door neighbors.  You must calculate and return the maximum amount of donations that can be collected.
//
//
//
// DEFINITION
// Class:BadNeighbors
// Method:maxDonations
// Parameters:vector <int>
// Returns:int
// Method signature:int maxDonations(vector <int> donations)
//
//
// CONSTRAINTS
// -donations contains between 2 and 40 elements, inclusive.
// -Each element in donations is between 1 and 1000, inclusive.
//
//
// EXAMPLES
//
// 0)
//  { 10, 3, 2, 5, 7, 8 }
//
// Returns: 19
//
// The maximum donation is 19, achieved by 10+2+7.  It would be better to take 10+5+8 except that
// the 10 and 8 donations are from neighbors.
//
// 1)
// { 11, 15 }
//
// Returns: 15
//
// 2)
// { 7, 7, 7, 7, 7, 7, 7 }
//
// Returns: 21
//
// 3)
// { 1, 2, 3, 4, 5, 1, 2, 3, 4, 5 }
//
// Returns: 16
//
// 4)
// { 94, 40, 49, 65, 21, 21, 106, 80, 92, 81, 679, 4, 61,
//   6, 237, 12, 72, 74, 29, 95, 265, 35, 47, 1, 61, 397,
//   52, 72, 37, 51, 1, 81, 45, 435, 7, 36, 57, 86, 81, 72 }
//
// Returns: 2926
//
// END KAWIGIEDIT TESTING


//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
