#include <bits/stdc++.h>

#define all(a)           a.begin(),a.end()
#define chng(a,b)       a^=b^=a^=b;
#define clr(y,z)        memset(y,z,sizeof(y))
#define cntbit(mask)     __builtin_popcount(mask)
#define CROSS(a,b,c,d) ((b.x-a.x)*(d.y-c.y)-(d.x-c.x)*(b.y-a.y))
#define fr(i,a,b)       for(i=a;i<=b;i++)
#define inf             (1e9)
#define mod             1000000007
#define ll              long long
#define oo              (1<<30)
#define pb              push_back
#define PI              3.141592653589793
#define pi              (2*acos(0))
#define pp              pop_back
#define rev(a)          reverse(all(a));
#define SIZE(s)         ((int)s.size())
#define saja(a)         sort(all(a))
#define sqr(a)          ((a)*(a))
#define SZ              50005
#define V(a)            vector<(a)>

using namespace std;

#define sz 101000
ll col[sz/64+10];
ll prime[sz], cnt;

void seive()//1 indexed
{
    long long i,j,k;
    for(i=3;i<sz;i+=2)
         if(!(col[i/64]&(1LL<<(i%64))))
                for(j=i*i;j<sz;j+=2*i)
                    col[j/64]|=(1LL<<(j%64));

    prime[cnt++]=2;
    for (int i = 3; i<sz; i+=2)
        if(!(col[i/64]&(1LL<<(i%64))))
            prime[cnt++] = i;
}

bool is_prime(ll i)
{
    if(i==2) return true;
    if(i%2==0) return false;
    if(!(col[i/64]&(1LL<<(i%64)))) return true;
    return false;
}

class Procrastination {
public:

    map<ll, set<ll> >factors;
    set<ll>fac;
    vector<ll>v;
    void gen(int x, int lim, ll now)
    {
        if(now>1e10) return;
        if(x==lim) fac.insert(now);
        gen(x+1,lim, now*v[x]);
        gen(x+1,lim, now);
    }

    void calcfact(ll n)
    {
        v.clear();
        ll now,nn=n;
        for (int i = 0; prime[i]*prime[i]<=n; i++)
        {
            if(n%prime[i]==0)
            {
                now = 1;
                while(n%prime[i]==0)
                {
                    n/=prime[i];
                    now*=prime[i];
                    v.pb(now);
                }
            }
        }
        fac.clear();
        gen(0,v.size(),1);
        factors[nn] = fac;
    }

	long long findFinalAssignee(long long n) {
        ll lim = sqrt(n+1);
        ll cur=n;
        int ind=cur;
        calcfact(cur);
        for (auto it = factors[ind].begin(); it!=factors[ind].end();it++)
        {
            if(cur%(*it)==0) {ind++;
//            cout<<i<<" + "<<cur<<endl;
            }
            else if((cur-1)%i==0) {cur--;
//            cout<<i<<" - "<<cur<<endl;
            }
//            lim = sqrt(cur+1);
            lim = cur/2+1;
//            cout<<i<<" = "<<cur<<endl;
        }

        return cur;
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit-pf 2.3.0
#include <iostream>
#include <string>
#include <vector>
#include <ctime>
#include <cmath>
using namespace std;
bool KawigiEdit_RunTest(int testNum, long long p0, bool hasAnswer, long long p1) {
	cout << "Test " << testNum << ": [" << p0;
	cout << "]" << endl;
	Procrastination *obj;
	long long answer;
	obj = new Procrastination();
	clock_t startTime = clock();
	answer = obj->findFinalAssignee(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p1 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	bool disabled;
	bool tests_disabled;
	all_right = true;
	tests_disabled = false;

	long long p0;
	long long p1;

//	// ----- test 0 -----
//	disabled = false;
//	p0 = 3ll;
//	p1 = 3ll;
//	all_right = (disabled || KawigiEdit_RunTest(0, p0, true, p1) ) && all_right;
//	tests_disabled = tests_disabled || disabled;
//	// ------------------
//
//	// ----- test 1 -----
//	disabled = false;
//	p0 = 8ll;
//	p1 = 11ll;
//	all_right = (disabled || KawigiEdit_RunTest(1, p0, true, p1) ) && all_right;
//	tests_disabled = tests_disabled || disabled;
//	// ------------------
//
//	// ----- test 2 -----
//	disabled = false;
//	p0 = 20ll;
//	p1 = 20ll;
//	all_right = (disabled || KawigiEdit_RunTest(2, p0, true, p1) ) && all_right;
//	tests_disabled = tests_disabled || disabled;
//	// ------------------
//
//	// ----- test 3 -----
//	disabled = false;
//	p0 = 196248ll;
//	p1 = 196259ll;
//	all_right = (disabled || KawigiEdit_RunTest(3, p0, true, p1) ) && all_right;
//	tests_disabled = tests_disabled || disabled;
//	// ------------------

	// ----- test 4 -----
	disabled = false;
	p0 = 5587021440ll;
	p1 = 5587021440ll;
	all_right = (disabled || KawigiEdit_RunTest(4, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------

	if (all_right) {
		if (tests_disabled) {
			cout << "You're a stud (but some test cases were disabled)!" << endl;
		} else {
			cout << "You're a stud (at least on given cases)!" << endl;
		}
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// You are working in the Huge Software Company.
// The company is so huge that it has an infinite number of employees.
// Employee number 1 is reserved for the Big Boss and Legendary Founder of the company, Mr. Z.
// Ordinary employees are numbered using positive integers, starting from 2.
//
// At the beginning of the day each employee is assigned a task they should accomplish:
// for each x from 2 to infinity, employee number x is assigned task number x.
// During the day some pairs of employees will swap the tasks they were assigned.
// The swapping follows a precise schedule that is described below.
//
// The working day in the Huge Software Company has infinitely many hours.
// The hours are numbered using positive integers, starting from 1.
// During hour 1 there are no swaps at all.
// During each of the following hours there are infinitely many swaps.
// These look as follows:
//
//
//
// During hour 2 we have the following swaps: workers 4 and 5 swap their tasks, workers 6 and 7 swap their tasks, workers 8 and 9 swap their tasks, and so on.
//
//
// During hour 3 we have the following swaps: workers 6 and 7 swap their tasks, workers 9 and 10 swap their tasks, workers 12 and 13 swap their tasks, and so on.
//
//
// ...
//
//
// Formally, for each h greater than or equal to 2, during hour h we look at all workers that have numbers divisible by h and strictly greater than h. Each of these workers will swap the task they currently have with the worker with a number one larger than their own.
//
//
//
// It can be shown that for each employee there is a finite number of hours after which the employee will never swap their current task with anyone.
// It can also be shown that for each task there is a finite number of hours after which the task will remain with the current employee forever.
//
// You are given a long long n.
// Compute and return the number of employee who will have the task number n at the end of the day.
//
// DEFINITION
// Class:Procrastination
// Method:findFinalAssignee
// Parameters:long long
// Returns:long long
// Method signature:long long findFinalAssignee(long long n)
//
//
// CONSTRAINTS
// -n will be between 2 and 10^10, inclusive.
//
//
// EXAMPLES
//
// 0)
// 3
//
// Returns: 3
//
// Employee 3 is never involved in any swaps: neither with employee 2, nor with employee 4.
//
// 1)
// 8
//
// Returns: 11
//
// Task 8 starts assigned to employee 8. During hour 2 this employee swaps it for another task with employee 9. During hour 3 employee 9 gives this task to employee 10. Finally, during hour 5 employee 10 gives this task to employee 11 where it will stay forever.
//
// 2)
// 20
//
// Returns: 20
//
// Task 20 goes from employee 20 to employee 21 (during hour 2), then to employee 22 (during hour 3), then back to employee 21 (during hour 7), and finally back to employee 20 (during hour 10). This is where it then remains forever.
//
// 3)
// 196248
//
// Returns: 196259
//
//
//
// 4)
// 5587021440
//
// Returns: 5587021440
//
//
//
// END KAWIGIEDIT TESTING
