#include <bits/stdc++.h>

#define all(a)           a.begin(),a.end()
#define chng(a,b)       a^=b^=a^=b;
#define clr(y,z)        memset(y,z,sizeof(y))
#define cntbit(mask)     __builtin_popcount(mask)
#define CROSS(a,b,c,d) ((b.x-a.x)*(d.y-c.y)-(d.x-c.x)*(b.y-a.y))
#define fr(i,a,b)       for(i=a;i<=b;i++)
#define inf             (1e9)
#define mod             1000000007
#define ll              long long
#define oo              (1<<30)
#define pb              push_back
#define PI              3.141592653589793
#define pi              (2*acos(0))
#define pp              pop_back
#define rev(a)          reverse(all(a));
#define SIZE(s)         ((int)s.size())
#define saja(a)         sort(all(a))
#define sqr(a)          ((a)*(a))
#define SZ              50005
#define V(a)            vector<(a)>

using namespace std;


int rr[] = {0,0,1,-1};
int cc[] = {1,-1,0,0};

class TheKingsArmyDiv2 {
public:
	int getNumber(vector <string> state) {
		int ans = 2,n=state.size();

		for (int i = 0; i<n; i++)
        {
            int m = state[i].size();
            for (int j = 0; j<m; j++)
            {
                if(state[i][j]=='H')
                {
                    ans = min(ans,1);
                    for (int k = 0; k<4; k++)
                    {
                        int u = i+rr[k];
                        int v = j+cc[k];
                        if(u<0||v<0||u>=n||v>=m) continue;
                        if(state[u][v]=='H') return 0;
                    }
                }
            }

        }

		return ans;
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit-pf 2.3.0
#include <iostream>
#include <string>
#include <vector>
#include <ctime>
#include <cmath>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, int p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	TheKingsArmyDiv2 *obj;
	int answer;
	obj = new TheKingsArmyDiv2();
	clock_t startTime = clock();
	answer = obj->getNumber(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p1 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	bool disabled;
	bool tests_disabled;
	all_right = true;
	tests_disabled = false;

	vector <string> p0;
	int p1;

	// ----- test 0 -----
	disabled = false;
	p0 = {"SSSSS","SSHHS","SSSSS"};
	p1 = 0;
	all_right = (disabled || KawigiEdit_RunTest(0, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------

	// ----- test 1 -----
	disabled = false;
	p0 = {"SSSSS","SSHSH","HSSSS"};
	p1 = 1;
	all_right = (disabled || KawigiEdit_RunTest(1, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------

	// ----- test 2 -----
	disabled = false;
	p0 = {"SSS","SSS","SSS"};
	p1 = 2;
	all_right = (disabled || KawigiEdit_RunTest(2, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------

	// ----- test 3 -----
	disabled = false;
	p0 = {"HSHSHSH","SSSHSSS","SSHSHSS","SHSHSHS"};
	p1 = 1;
	all_right = (disabled || KawigiEdit_RunTest(3, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------

	// ----- test 4 -----
	disabled = false;
	p0 = {"HHSH","HHHS","HSSS","SHSH","HHHS","HSHH","SSSH"};
	p1 = 0;
	all_right = (disabled || KawigiEdit_RunTest(4, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------

	if (all_right) {
		if (tests_disabled) {
			cout << "You're a stud (but some test cases were disabled)!" << endl;
		} else {
			cout << "You're a stud (at least on given cases)!" << endl;
		}
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
//
// The King of Byteland has an army that consists of R*C soldiers.
// He has just arranged the soldiers into a grid with R rows and C columns.
// Two soldiers are neighbors if they stand next to each other in a row or in a column.
//
//
//
//
// Each of the soldiers is currently either happy or sad.
// You are given their current states in a vector <string> state with R elements, each containing C characters.
// The character state[i][j] is either 'H' (if the soldier in row i, column j is happy) or 'S' (if that soldier is sad).
//
//
//
//
// Happiness is contagious.
// Whenever two neighbors are both happy, they will tell each other jokes and after a minute that will make all of their neighbors happy as well.
//
//
//
//
// Here's an example.
// There are two happy neighbors among many sad soldiers:
//
//
//
//
// {"SSSSS",
//  "SSHHS",
//  "SSSSS"}
//
//
//
//
// This is the situation after one minute: all of their neighbors are happy now.
//
//
//
//
// {"SSHHS",
//  "SHHHH",
//  "SSHHS"}
//
//
//
//
// And this is the situation after another minute. Now all the neighbors of the soldiers that are currently happy became happy as well.
//
//
//
//
// {"SHHHH",
//  "HHHHH",
//  "SHHHH"}
//
//
//
//
// After another minute, all the soldiers in the King's army would be happy.
//
//
//
//
// The King wants all his soldiers to be happy.
// Sometimes it's easy, as in the above example: all he has to do is wait for a while and all soldiers will become happy.
// However, it is not always the case.
// For example, in the situation below the happiness would not spread anywhere, each soldier would remain in his original state forever.
// (Note that a single happy soldier does not make his neighbors happy.)
//
//
//
//
// {"SSSSS",
//  "SSHSH",
//  "HSSSS"}
//
//
//
//
// The King can make a soldier happy by giving him an award for excellent service.
// Obviously, the King could make all soldiers happy by giving awards to all of them.
// But the King is smart and knows that there is a better solution.
// He will only give the awards to a few carefully selected soldiers and then he will simply wait until the happiness spreads to the rest of the army.
//
//
//
//
// You are given the vector <string> state.
// Compute and return the smallest number of awards the king has to give to make all soldiers happy in the end.
//
//
// DEFINITION
// Class:TheKingsArmyDiv2
// Method:getNumber
// Parameters:vector <string>
// Returns:int
// Method signature:int getNumber(vector <string> state)
//
//
// CONSTRAINTS
// -state will contain between 3 and 50 elements, inclusive.
// -Each element of state will contain between 3 and 50 characters, inclusive.
// -Each element of state will contain the same number of characters.
// -Each character in each element of state will be either 'H' or 'S'.
//
//
// EXAMPLES
//
// 0)
// {"SSSSS",
//  "SSHHS",
//  "SSSSS"}
//
// Returns: 0
//
// This is the first example in the problem statement. No awards are necessary, all soldiers will become happy anyway.
//
// 1)
// {"SSSSS",
//  "SSHSH",
//  "HSSSS"}
//
// Returns: 1
//
// This is the second example in the problem statement. The King needs to give at least one award. One optimal solution is to give an award to the soldier in row 1, column 3. (Both indices are 0-based.)
//
// 2)
// {"SSS",
//  "SSS",
//  "SSS"}
//
// Returns: 2
//
// Here the King must give awards to two soldiers.
//
// 3)
// {"HSHSHSH", "SSSHSSS", "SSHSHSS", "SHSHSHS"}
//
// Returns: 1
//
//
//
// 4)
// {"HHSH", "HHHS", "HSSS", "SHSH", "HHHS", "HSHH", "SSSH"}
//
// Returns: 0
//
//
//
// END KAWIGIEDIT TESTING
