#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstring>
#define ll long long
#define clr(y,z)        memset(y,z,sizeof(y))
using namespace std;


class ColorfulCoinsEasy
{
public:
    int dp[15][(1<<16)], nmask , len;
    bool flag;
    vector<int>val;
    void print_mask(string s, int mask)
    {
        cout<<s<<"------------------"<<endl;
        for (int i = 0; i<val.size(); i++)
            cout<<(((1<<i)&mask)>0?1:0)<<" ";
        cout<<endl;
        cout<<s<<"------------------"<<endl;
    }

    int rec(int pos, int mask)
    {
//        cout<<pos<<": "<<endl;
//        print_mask("here",mask);
        if(flag == true) return 0;
        if(mask==nmask)
        {
            flag = true;
            return true;
        }
        if(pos<0) return false;
        if(dp[pos][mask]!=-1) return dp[pos][mask];
        int &ret = dp[pos][mask];
        ret = false;
        ll k;
        for (int i = 0; i<len; i++)
        {
//            print_mask("now",mask);
            k =val[pos]*(ll)(i+1);
            if(!((1<<i)&mask) && k<val[pos+1])
            {
                ret|= rec(pos-1,(1<<i)|mask);
            }
        }
        return ret;
    }


    string isPossible(vector <int> values)
    {
        flag = false;
        val = values;
        len = values.size();
        clr(dp,-1);
        nmask = (1<<len)-1;
//        cout<<nmask<<":L "<<endl;
//        print_mask("main section",nmask);
        rec(len-2,(1<<(len-1)));
        if(flag == false) return "Impossible";
        return "Possible";
    }
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <int> p0, bool hasAnswer, string p1)
{
    cout << "Test " << testNum << ": [" << "{";
    for (int i = 0; int(p0.size()) > i; ++i)
    {
        if (i > 0)
        {
            cout << ",";
        }
        cout << p0[i];
    }
    cout << "}";
    cout << "]" << endl;
    ColorfulCoinsEasy *obj;
    string answer;
    obj = new ColorfulCoinsEasy();
    clock_t startTime = clock();
    answer = obj->isPossible(p0);
    clock_t endTime = clock();
    delete obj;
    bool res;
    res = true;
    cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
    if (hasAnswer)
    {
        cout << "Desired answer:" << endl;
        cout << "\t" << "\"" << p1 << "\"" << endl;
    }
    cout << "Your answer:" << endl;
    cout << "\t" << "\"" << answer << "\"" << endl;
    if (hasAnswer)
    {
        res = answer == p1;
    }
    if (!res)
    {
        cout << "DOESN'T MATCH!!!!" << endl;
    }
    else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2)
    {
        cout << "FAIL the timeout" << endl;
        res = false;
    }
    else if (hasAnswer)
    {
        cout << "Match :-)" << endl;
    }
    else
    {
        cout << "OK, but is it right?" << endl;
    }
    cout << "" << endl;
    return res;
}
int main()
{
    bool all_right;
    all_right = true;

    #ifdef ENAM
//    freopen("output.txt","w",stdout);
    #endif // ENAM

    vector <int> p0;
    string p1;

    {
        // ----- test 0 -----
        int t0[] = {1};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        p1 = "Possible";
        all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
        // ------------------
    }

    {
        // ----- test 1 -----
        int t0[] = {1,3};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        p1 = "Possible";
        all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
        // ------------------
    }

    {
        // ----- test 2 -----
        int t0[] = {1,2,4};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        p1 = "Impossible";
        all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
        // ------------------
    }

    {
        // ----- test 3 -----
        int t0[] = {1,5,15,90};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        p1 = "Possible";
        all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
        // ------------------
    }

    {
        // ----- test 4 -----
        int t0[] = {1,4,20,60,180,1440,5760};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        p1 = "Impossible";
        all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
        // ------------------
    }

    {
        // ----- test 5 -----
        int t0[] = {1,7,21,105,630,3150,18900};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        p1 = "Possible";
        all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
        // ------------------
    }

    {
        // ----- test 6 -----
        int t0[] = {1,10,30,300,900,9000,18000};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        p1 = "Impossible";
        all_right = KawigiEdit_RunTest(6, p0, true, p1) && all_right;
        // ------------------
    }

    {
        // ----- test 7 -----
        int t0[] = {1,2,10,40,200,1000,4000,20000};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        p1 = "Impossible";
        all_right = KawigiEdit_RunTest(7, p0, true, p1) && all_right;
        // ------------------
    }

    if (all_right)
    {
        cout << "You're a stud (at least on the example cases)!" << endl;
    }
    else
    {
        cout << "Some of the test cases had errors." << endl;
    }
    return 0;
}
// PROBLEM STATEMENT
// The currency system in Colorland consists of various types of coins. The coin denominations follow these simple rules:
//
//
// The denominations are distinct positive integers.
// There is a coin type with denomination 1.
// For each pair of different coin types, the denomination of one coin type divides the denomination of the other one.
//
//
// You are given a int[] values containing all the available denominations in ascending order.
//
// Coins of different denominations look exactly the same except that they have different colors. Each coin in Colorland has exactly one color. The coin colors follow these even simpler rules:
//
//
// All coins of the same type are of the same color.
// No two coins of different types are of the same color.
//
//
// You know all coin denominations used in Colorland, but you don't know their colors. You don't even know the set of colors used on the coins.
//
// For each denomination, you'd like to know the color of coins of this denomination. To accomplish this, you've got a credit card with an infinite amount of money. You can perform a single query to an ATM which can also provide you with an infinite amount of money. The query is described by a positive integer X, which means that you want to receive exactly X units of money from the ATM. The ATM will provide you with the requested amount. You also know that the requested amount will be paid using the smallest possible number of coins. (Note that this rule always uniquely determines the set of coins chosen to make the payment.)
//
// Return "Possible" (quotes for clarity) if it's possible to determine the color of coins of each denomination, and return "Impossible" otherwise.
//
//
// DEFINITION
// Class:ColorfulCoinsEasy
// Method:isPossible
// Parameters:vector <int>
// Returns:string
// Method signature:string isPossible(vector <int> values)
//
//
// CONSTRAINTS
// -values will contain between 1 and 15 elements, inclusive.
// -Each element of values will be between 1 and 20000, inclusive.
// -values will be sorted in strictly ascending order. Note that this also implies that all the elements of values will be distinct.
// -For each pair of different elements in values, the smaller one will be a divisor of the larger one.
// -values[0] will be 1.
//
//
// EXAMPLES
//
// 0)
// {1}
//
// Returns: "Possible"
//
// For any positive X, you'll get exactly X coins of denomination 1, so you'll easily learn their color.
//
// 1)
// {1, 3}
//
// Returns: "Possible"
//
// X = 5 is one possible solution. As the ATM gives the smallest number of coins, it will give one coin of denomination 3 and two coins of denomination 1. That means, for example, that if you get one red coin and two blue coins, you'll understand that coins of denomination 3 are red, and coins of denomination 1 are blue.
//
// 2)
// {1, 2, 4}
//
// Returns: "Impossible"
//
// It can be proven that for any X, you'll get at most one coin of denomination 1, and at most one coin of denomination 2. If you get no coins of some denomination, clearly you won't be able to determine their color. However, if you get one coin from each of denominations 1 and 2, you won't be able to find out which of the two colors represents which denomination.
//
// 3)
// {1, 5, 15, 90}
//
// Returns: "Possible"
//
// X = 504 is one possible solution. You'll get five coins of denomination 90, three coins of denomination 15, one coin of denomination 5 and four coins of denomination 1.
//
// 4)
// {1, 4, 20, 60, 180, 1440, 5760}
//
// Returns: "Impossible"
//
//
//
// 5)
// {1, 7, 21, 105, 630, 3150, 18900}
//
// Returns: "Possible"
//
// X = 137969 is the smallest possible solution.
//
// 6)
// {1, 10, 30, 300, 900, 9000, 18000}
//
// Returns: "Impossible"
//
//
//
// 7)
// {1, 2, 10, 40, 200, 1000, 4000, 20000}
//
// Returns: "Impossible"
//
//
//
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
