#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstring>
#include <cctype>
#include <fstream>

#define sz 100
#define pb(a) push_back(a)
#define pp pop_back()
#define ll long long
#define fread freopen("input.txt","r",stdin)
#define fwrite freopen("output.txt","w",stdout)
#define inf (1<<30-1)
#define clr(abc,z) memset(abc,z,sizeof(abc))
#define PI acos(-1)

using namespace std;

class PipeCuts {
public:

    int nCr[100][4];
    int rec(int n, int r)
    {
        if(n==1 || n==r) return 1;
        if(r == 1) return n;
        int &ret = nCr[n][r];
        if(ret!=-1) return ret;
        ret = rec(n-1,r)+rec(n-1, r-1);
        return ret;
    }


	double probability(vector <int> weldLocations, int L) {
		clr(nCr,-1);
		int len = weldLocations.size(), a, b, c;
		int total = rec(len,2), cnt=0;
		for (int i = 0; i<len; i++)
        {
            for (int j = i+1; j<len; j++)
            {
                a = min(weldLocations[i], weldLocations[j]);
                b = max(weldLocations[i], weldLocations[j]);
                c = 100 - b;
                b-=a;

                if(a>L||b>L||c>L) cnt++;
            }
        }
//        cout<<cnt<<" "<<total<<endl;
        double ans = (cnt*1.0)/(total*1.0);
        return ans;
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <int> p0, int p1, bool hasAnswer, double p2) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p0[i];
	}
	cout << "}" << "," << p1;
	cout << "]" << endl;
	PipeCuts *obj;
	double answer;
	obj = new PipeCuts();
	clock_t startTime = clock();
	answer = obj->probability(p0, p1);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p2 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == answer && fabs(p2 - answer) <= 1e-9 * max(1.0, fabs(p2));
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;

	vector <int> p0;
	int p1;
	double p2;

	{
	// ----- test 0 -----
	int t0[] = {25,50,75};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 25;
	p2 = 1.0;
	all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
	// ------------------
	}

	{
	// ----- test 1 -----
	int t0[] = {25,50,75};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 50;
	p2 = 0.0;
	all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
	// ------------------
	}

	{
	// ----- test 2 -----
	int t0[] = {25,50,75};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 24;
	p2 = 1.0;
	all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
	// ------------------
	}

	{
	// ----- test 3 -----
	int t0[] = {99,88,77,66,55,44,33,22,11};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 50;
	p2 = 0.7222222222222222;
	all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
	// ------------------
	}

	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// A 100 meter long pipe must be cut in two places.  It can only be cut at certain places, where it was originally welded from smaller pipes.  If the two cut locations are chosen at random (each potential location has equal probability of being chosen), find the probability of a resulting pipe being longer than L meters.
//
//
// Create a method named probability that accepts a int[] weldLocations and int L as parameters.  It should calculate the probability of one or more resulting pipes being strictly longer than L if the two cut locations are chosen at random from weldLocations.  Each element in weldLocations represents the number of meters from the left end of the pipe.
//
// DEFINITION
// Class:PipeCuts
// Method:probability
// Parameters:vector <int>, int
// Returns:double
// Method signature:double probability(vector <int> weldLocations, int L)
//
//
// NOTES
// -Your return value must have a relative or absolute error less than 1e-9.
//
//
// CONSTRAINTS
// -weldLocations will have between 2 and 50 elements, inclusive.
// -Each element in weldLocations will be between 1 and 99, inclusive.
// -weldLocations will not contain duplicate elements.
// -L will be between 1 and 100, inclusive.
//
//
// EXAMPLES
//
// 0)
// {25, 50, 75}
// 25
//
// Returns: 1.0
//
// Any random set of cuts results in a pipe being longer than 25 meters.
//
// 1)
// {25, 50, 75}
// 50
//
// Returns: 0.0
//
// This time, it is impossible to cut the pipe such that some resulting pipe is longer than 50 meters.
//
// 2)
// {25, 50, 75}
// 24
//
// Returns: 1.0
//
// 3)
// {99, 88, 77, 66, 55, 44, 33, 22, 11}
// 50
//
// Returns: 0.7222222222222222
//
// END KAWIGIEDIT TESTING


//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
